[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8888

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
