[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios"]
  directory = "netlify/functions"
  included_files = ["netlify/functions/fetchSwiggyData.js"]

[dev]
  framework = "react"
  command = "npm start"
  targetPort = 3000
  port = 8888

[build.environment]
  NODE_VERSION = "18"
